name: Generate Projects Metrics

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: github-metrics.svg
          base: ""
          plugin_repositories: yes
          plugin_repositories_featured: Rayyan-Rizwan/plant-disease-detector, Rayyan-Rizwan/movie-rec
          plugin_repositories_pinned: 4
          plugin_repositories_order: featured, pinned, starred
          config_theme: tokyonight
